name: Setup .NET and Clang
description: Set up .NET and Clang (.so resolution and headers) for ClangSharp P/Invoke generation on Linux

runs:
  using: composite
  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v5

    - name: Set up Clang (.so resolution and headers)
      shell: bash
      run: |
        # Extract the ClangSharpPInvokeGenerator major version from dotnet-tools.json
        dotnet tool restore
        clang_tool_version=$(jq -r '.tools.clangsharppinvokegenerator.version' dotnet-tools.json | cut -d'.' -f1)
        echo "Detected ClangSharp version: $clang_tool_version"

        # Install clang headers
        sudo apt-get update && sudo apt-get install -y wget gnupg lsb-release
        wget -qO llvm.key https://apt.llvm.org/llvm-snapshot.gpg.key
        sudo gpg --dearmor -o /etc/apt/keyrings/llvm.gpg llvm.key
        echo "deb [signed-by=/etc/apt/keyrings/llvm.gpg] http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-${clang_tool_version} main" | sudo tee /etc/apt/sources.list.d/llvm${clang_tool_version}.list
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libclang-common-${clang_tool_version}-dev