using System.Text;
using System.Text.RegularExpressions;

// File-based entry point used by the MSBuild generation target.
if (args.Length == 1 && (args[0] == "--help" || args[0] == "-h"))
{
    Console.WriteLine("Usage: dotnet run GenerateDebuggerProxies.cs -- <NativeMethods.cs> <output.cs>");
    return 0;
}
if (args.Length == 1 && args[0] == "--self-test")
{
    DebuggerGenerator.SelfTest();
    Console.WriteLine("Debugger proxy generator self-test passed.");
    return 0;
}
if (args.Length != 2)
{
    Console.Error.WriteLine("Usage: dotnet run GenerateDebuggerProxies.cs -- <NativeMethods.cs> <output.cs>");
    return 1;
}
var result = DebuggerGenerator.Generate(File.ReadAllText(args[0]));
Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(args[1]))!);
File.WriteAllText(args[1], result, new UTF8Encoding(false));
Console.WriteLine($"Generated debugger proxies: {args[1]}");
return 0;

static class DebuggerGenerator
{
    private static readonly Dictionary<string, string[]> Schemas = new()
    {
        ["b3WorldId"] = ["index1", "generation"], ["b3BodyId"] = ["index1", "world0", "generation"],
        ["b3ShapeId"] = ["index1", "world0", "generation"], ["b3JointId"] = ["index1", "world0", "generation"],
        ["b3ContactId"] = ["index1", "world0", "generation"], ["b3Vec2"] = ["x", "y"],
        ["b3Vec3"] = ["x", "y", "z"], ["b3Quat"] = ["v", "s"], ["b3Transform"] = ["p", "q"],
        ["b3AABB"] = ["lowerBound", "upperBound"]
    };
    private static readonly string[] Ids = ["b3WorldId", "b3BodyId", "b3ShapeId", "b3JointId", "b3ContactId"];
    private static readonly Regex Struct = new(@"public\s+(?:unsafe\s+)?partial\s+struct\s+(?<name>b3\w+)\s*\{(?<body>.*?)\}", RegexOptions.Compiled | RegexOptions.Singleline);
    private static readonly Regex Field = new(@"public\s+(?:readonly\s+)?[\w<>,.?]+(?:\s*\*)?\s+(?<name>\w+)\s*;", RegexOptions.Compiled);
    private static readonly Regex Method = new(@"public\s+static\s+extern\s+(?<ret>[\w<>,.?]+(?:\s*\*)?)\s+(?<method>b3(?:World|Body|Shape|Joint|Contact)_(?<op>Get|Is|Are|Set|Enable|Disable)\w*)\s*\((?<params>[^;\n]*)\)\s*;", RegexOptions.Compiled);
    private sealed record Param(string Type, string Name);
    private sealed record Api(string ReturnType, string Method, string Op, string Id, Param[] Params);

    public static string Generate(string native)
    {
        var structs = Struct.Matches(native).ToDictionary(m => m.Groups["name"].Value, m => Field.Matches(m.Groups["body"].Value).Select(f => f.Groups["name"].Value).ToHashSet());
        foreach (var s in Schemas) if (!structs.TryGetValue(s.Key, out var fields) || s.Value.Any(f => !fields.Contains(f))) throw new InvalidOperationException($"Debugger schema missing for {s.Key}: expected fields {string.Join(", ", s.Value)}.");
        var apis = Method.Matches(native).Select(Parse).Where(a => a is not null).Cast<Api>().ToArray();
        foreach (var id in Ids)
            if (!apis.Any(a => a.Id == id && a.Method == $"b3{id[2..^2]}_IsValid" && a.ReturnType == "bool" && a.Params.Length == 1))
                throw new InvalidOperationException($"Debugger API missing for {id}: expected b3{id[2..^2]}_IsValid({id} id) returning bool.");
        var sb = new StringBuilder("// <auto-generated />\nusing System.CodeDom.Compiler;\nusing System.Diagnostics;\n\nnamespace Box3D;\n\n");
        foreach (var id in Ids)
        {
            var fields = Schemas[id]; sb.AppendLine("[GeneratedCode(\"Box3D.DebuggerGenerator\", \"2\")]"); sb.AppendLine($"[DebuggerDisplay(\"{id} {string.Join(":", fields.Select(f => "{" + f + "}"))}\")]"); sb.AppendLine($"[DebuggerTypeProxy(typeof({id}DebugView))]"); sb.AppendLine($"public partial struct {id} {{ }}\ninternal sealed class {id}DebugView {{"); sb.AppendLine($"    [DebuggerBrowsable(DebuggerBrowsableState.Never)] private readonly {id} _id;\n    public {id}DebugView({id} id) => _id = id;");
            foreach (var a in apis.Where(a => a.Id == id && a.Params.Length == 1 && a.ReturnType != "void" && !a.ReturnType.Contains('*')))
            {
                var suffix = a.Method[(a.Method.IndexOf('_') + 1)..]; var property = a.Op == "Get" ? suffix[3..] : suffix; var setter = FindSetter(apis, a, property);
                var getter = property == "IsValid" ? $"Box3D.{a.Method}(_id)" : $"IsValid ? Box3D.{a.Method}(_id) : default";
                sb.Append($"    public {a.ReturnType} {property} {{ get => {getter}; "); if (setter is not null) sb.Append(setter.StartsWith("set ", StringComparison.Ordinal) ? setter + " " : $"set => {setter}; "); sb.AppendLine("}");
            }
            sb.AppendLine("}\n");
        }
        foreach (var v in Schemas.Where(x => !Ids.Contains(x.Key))) { sb.AppendLine("[GeneratedCode(\"Box3D.DebuggerGenerator\", \"2\")]"); sb.AppendLine($"[DebuggerDisplay(\"{v.Key} {string.Join(", ", v.Value.Select(f => "{" + f + "}"))}\")]"); sb.AppendLine($"public partial struct {v.Key} {{ }}\n"); }
        return sb.ToString().Replace("b3Vec2 {x}, {y}", "b3Vec2({x},{y})", StringComparison.Ordinal).Replace("b3Vec3 {x}, {y}, {z}", "b3Vec3({x},{y},{z})", StringComparison.Ordinal).Replace("b3Quat {v}, {s}", "b3Quat({v},{s})", StringComparison.Ordinal).Replace("b3Transform {p}, {q}", "b3Transform({p},{q})", StringComparison.Ordinal).Replace("b3AABB {lowerBound}, {upperBound}", "b3AABB({lowerBound},{upperBound})", StringComparison.Ordinal);
    }
    private static string? FindSetter(Api[] all, Api g, string property)
    {
        var prefix = g.Method[..g.Method.IndexOf('_')]; Api? s = null;
        if (g.Op == "Get") s = all.FirstOrDefault(a => a.Method == prefix + "_Set" + property && Compatible(a, g.Id, g.ReturnType));
        if (g.Op == "Is") s = all.FirstOrDefault(a => a.Method == prefix + "_Set" + property[2..] && Compatible(a, g.Id, g.ReturnType));
        if (g.Op == "Are" && property.StartsWith("Are", StringComparison.Ordinal) && property.EndsWith("Enabled", StringComparison.Ordinal)) s = all.FirstOrDefault(a => a.Method == prefix + "_Enable" + property[3..^7] && Compatible(a, g.Id, "bool"));
        if (g.Op == "Is" && property.EndsWith("Enabled", StringComparison.Ordinal)) s = all.FirstOrDefault(a => a.Method == prefix + "_Enable" + property[2..^7] && Compatible(a, g.Id, "bool"));
        if (g.Op == "Is" && property == "IsEnabled") { var en = all.FirstOrDefault(a => a.Method == prefix + "_Enable" && a.Params.Length == 1); var dis = all.FirstOrDefault(a => a.Method == prefix + "_Disable" && a.Params.Length == 1); if (en is not null && dis is not null) return $"set {{ if (value) Box3D.{en.Method}(_id); else Box3D.{dis.Method}(_id); }}"; }
        return s is null ? null : $"Box3D.{s.Method}(_id, value)";
    }
    private static bool Compatible(Api a, string id, string type) => a.Id == id && a.ReturnType == "void" && a.Params.Length == 2 && a.Params[1].Type == type;
    private static Api? Parse(Match m) { var p = Split(m.Groups["params"].Value).Select(ParseParam).ToArray(); return p.Length > 0 && p.All(x => x is not null) ? new(m.Groups["ret"].Value, m.Groups["method"].Value, m.Groups["op"].Value, p[0]!.Type, p!.Cast<Param>().ToArray()) : null; }
    private static Param? ParseParam(string s) { s = Regex.Replace(s, @"\[[^\]]*\]\s*", "").Trim(); var m = Regex.Match(s, @"(?<type>[\w<>,.?]+(?:\s*\*)?)\s+(?<name>\w+)$"); return m.Success ? new(m.Groups["type"].Value, m.Groups["name"].Value) : null; }
    private static IEnumerable<string> Split(string s) => Regex.Split(s, @",\s*(?![^<]*>)").Where(x => !string.IsNullOrWhiteSpace(x));

    public static void SelfTest()
    {
        var sample = string.Join(' ', Schemas.Select(s => $"public partial struct {s.Key} {{ {string.Join(' ', s.Value.Select(f => $"public float {f};"))} }}")) + " public static extern float b3World_GetGravity(b3WorldId id); public static extern void b3World_SetGravity(b3WorldId id, [NativeTypeName(\"_Bool\")] bool flag); public static extern bool b3World_IsSleepingEnabled(b3WorldId id); public static extern void b3World_EnableSleeping(b3WorldId id, [NativeTypeName(\"_Bool\")] bool flag); public static extern bool b3Shape_AreSensorEventsEnabled(b3ShapeId id); public static extern void b3Shape_EnableSensorEvents(b3ShapeId id, [NativeTypeName(\"_Bool\")] bool flag); public static extern b3Vec3 b3Body_GetLocalPoint(b3BodyId id, b3Vec3 point); public static extern void* b3World_GetUserData(b3WorldId id); public static extern int b3World_GetMany(b3WorldId id, int a);";
        sample += " public static extern bool b3World_IsValid(b3WorldId id); public static extern bool b3Body_IsValid(b3BodyId id); public static extern bool b3Shape_IsValid(b3ShapeId id); public static extern bool b3Joint_IsValid(b3JointId id); public static extern bool b3Contact_IsValid(b3ContactId id); public static extern bool b3Body_IsAwake(b3BodyId id); public static extern void b3Body_SetAwake(b3BodyId id, [NativeTypeName(\"_Bool\")] bool awake); public static extern bool b3Body_IsEnabled(b3BodyId id); public static extern void b3Body_Enable(b3BodyId id); public static extern void b3Body_Disable(b3BodyId id);";
        sample += " public static extern float b3World_GetFoo(b3WorldId id); public static extern void b3World_SetFoo(b3WorldId id, float value); public static extern b3Vec3 b3Body_GetPosition(b3BodyId id);";
        var x = Generate(sample);
        Require(x, "b3WorldId {index1}:{generation}", "world ID display");
        Require(x, "b3Vec3({x},{y},{z})", "value display");
        Require(x, "set => Box3D.b3World_SetFoo(_id, value)", "Get/Set pairing");
        Require(x, "set => Box3D.b3Body_SetAwake(_id, value)", "Is/Set pairing");
        Require(x, "set => Box3D.b3World_EnableSleeping(_id, value)", "IsEnabled/Enable pairing");
        Require(x, "set => Box3D.b3Shape_EnableSensorEvents(_id, value)", "Are/Enable pairing");
        Require(x, "public bool IsValid { get => Box3D.b3Body_IsValid(_id);", "direct IsValid getter");
        Require(x, "public b3Vec3 Position { get => IsValid ? Box3D.b3Body_GetPosition(_id) : default;", "validity-gated getter");
        Require(x, "if (value) Box3D.b3Body_Enable(_id); else Box3D.b3Body_Disable(_id);", "IsEnabled action setter");
        Reject(x, "GetMany", "multi-parameter getter");
        Reject(x, "GetUserData", "pointer getter");
        if (x.Contains("index2") || x != Generate(sample)) throw new InvalidOperationException("Self-test failed: unexpected ID field or nondeterministic output.");
        try { Generate(sample.Replace("public float z;", "", StringComparison.Ordinal)); throw new InvalidOperationException("Self-test failed: missing schema was not rejected."); } catch (InvalidOperationException e) when (e.Message.Contains("schema missing", StringComparison.Ordinal)) { }
    }

    private static void Require(string output, string fragment, string name)
    {
        if (!output.Contains(fragment, StringComparison.Ordinal))
            throw new InvalidOperationException($"Self-test failed: missing {name} fragment '{fragment}'.");
    }

    private static void Reject(string output, string fragment, string name)
    {
        if (output.Contains(fragment, StringComparison.Ordinal))
            throw new InvalidOperationException($"Self-test failed: unexpected {name} fragment '{fragment}'.");
    }
}
